#!/usr/bin/env python3
"""scripts/report.py -- parses results/build/*.rpt (real Vivado output, one
build's worth, gitignored per master spec S13's "generated does not go in
version control" rule) into the checked-in results/*.md tables results/
README.md already declares. Run after scripts/build.tcl produces a fresh
results/build/*.rpt set.

Usage:
    python scripts/report.py

Writes results/timing.md and results/utilization.md. Does NOT invent numbers
for reports that don't exist yet (ml_metrics.md needs a trained S4 model;
latency_histogram.csv and ila_captures/ need real hardware, S11) -- it only
turns what Vivado actually measured into the tables master spec S12 requires,
and leaves everything else alone.
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BUILD_DIR = REPO_ROOT / "results" / "build"
OUT_DIR = REPO_ROOT / "results"


def read(name):
    p = BUILD_DIR / name
    if not p.exists():
        return None
    return p.read_text(encoding="utf-8", errors="replace")


def parse_timing(text):
    """Design Timing Summary table: WNS/TNS/.../WHS/THS/.../WPWS/TPWS/..."""
    m = re.search(
        r"^\s*([\d.-]+)\s+([\d.-]+)\s+(\d+)\s+(\d+)\s+"
        r"([\d.-]+)\s+([\d.-]+)\s+(\d+)\s+(\d+)\s+"
        r"([\d.-]+)\s+([\d.-]+)\s+(\d+)\s+(\d+)\s*$",
        text, re.MULTILINE,
    )
    if not m:
        return None
    wns, tns, tns_fail, tns_total, whs, ths, ths_fail, ths_total, \
        wpws, tpws, tpws_fail, tpws_total = m.groups()
    clk = re.search(
        r"^(\S+)\s+\{[^}]*\}\s+([\d.]+)\s+([\d.]+)\s*$", text, re.MULTILINE
    )
    period_ns = float(clk.group(2)) if clk else None
    # Achieved Fmax = 1 / (constrained period - worst setup slack), not the
    # constrained clock's own nominal frequency (which is just NFR-1's target).
    fmax_mhz = (1000.0 / (period_ns - float(wns))) if period_ns else None
    return {
        "wns": float(wns), "tns": float(tns),
        "tns_fail": int(tns_fail), "tns_total": int(tns_total),
        "whs": float(whs), "ths": float(ths),
        "ths_fail": int(ths_fail), "ths_total": int(ths_total),
        "period_ns": period_ns, "fmax_mhz": fmax_mhz,
        "clock_name": clk.group(1) if clk else None,
    }


def parse_worst_path(text, label):
    """First 'Max Delay Paths' / 'Min Delay Paths' block's Source/Destination
    and one-line delay summary, for the top-level rx_clk->rx_clk group only
    (the first occurrence in the file)."""
    block = re.search(
        label + r" Paths\n-+\nSlack \(MET\)\s*:\s*([\d.-]+)ns.*?\n"
        r"\s*Source:\s*(\S+)\n.*?\n"
        r"\s*Destination:\s*(\S+)\n",
        text, re.DOTALL,
    )
    if not block:
        return None
    return {
        "slack_ns": float(block.group(1)),
        "source": block.group(2),
        "destination": block.group(3),
    }


def parse_utilization(text):
    def cell(pattern):
        m = re.search(pattern, text, re.MULTILINE)
        return m.groups() if m else None

    lut = cell(r"^\| Slice LUTs\s*\*?\s*\|\s*(\d+)\s*\|.*?\|\s*(\d+)\s*\|\s*([\d.]+)\s*\|$")
    ff = cell(r"^\| Slice Registers\s*\|\s*(\d+)\s*\|.*?\|\s*(\d+)\s*\|\s*([\d.]+)\s*\|$")
    bram = cell(r"^\| Block RAM Tile\s*\|\s*([\d.]+)\s*\|.*?\|\s*(\d+)\s*\|\s*([\d.]+)\s*\|$")
    dsp = cell(r"^\| DSPs\s*\|\s*(\d+)\s*\|.*?\|\s*(\d+)\s*\|\s*([\d.]+)\s*\|$")
    return {"lut": lut, "ff": ff, "bram": bram, "dsp": dsp}


def fmt_row(name, tup, unit=""):
    if tup is None:
        return f"| {name} | -- | -- | -- |"
    used, avail, pct = tup
    return f"| {name} | {used}{unit} | {avail}{unit} | {pct}% |"


def write_timing_md(timing_text):
    t = parse_timing(timing_text)
    if t is None:
        print("WARN: could not parse Design Timing Summary from timing_summary.rpt", file=sys.stderr)
        return False
    worst_setup = parse_worst_path(timing_text, "Max Delay")
    worst_hold = parse_worst_path(timing_text, "Min Delay")

    lines = []
    lines.append("# results/timing.md")
    lines.append("")
    lines.append("Generated by `scripts/report.py` from `results/build/timing_summary.rpt`")
    lines.append("(real Vivado `report_timing_summary` output on the routed `tob_top` design,")
    lines.append(f"`{t['clock_name']}` at {t['period_ns']:.3f} ns / {t['fmax_mhz']:.3f} MHz, per master spec S12.3).")
    lines.append("Do not hand-edit; re-run the script after a new build.")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("| :-- | --: |")
    lines.append(f"| WNS (setup) | {t['wns']:.3f} ns |")
    lines.append(f"| TNS (setup) | {t['tns']:.3f} ns |")
    lines.append(f"| Setup failing endpoints | {t['tns_fail']} / {t['tns_total']} |")
    lines.append(f"| WHS (hold) | {t['whs']:.3f} ns |")
    lines.append(f"| THS (hold) | {t['ths']:.3f} ns |")
    lines.append(f"| Hold failing endpoints | {t['ths_fail']} / {t['ths_total']} |")
    lines.append(f"| Achieved Fmax ({t['clock_name']}) | {t['fmax_mhz']:.3f} MHz (period {t['period_ns']:.3f} ns) |")
    lines.append("")
    lines.append("**All user-specified timing constraints are met (0 failing endpoints, both setup and hold).**")
    lines.append("")
    if worst_setup:
        lines.append(f"Worst setup path: slack **{worst_setup['slack_ns']:.3f} ns** — "
                      f"`{worst_setup['source']}` → `{worst_setup['destination']}` "
                      f"(order_builder's TX payload register into the latency histogram's "
                      f"distributed-RAM write port; see `docs/design_decisions.md` D26-D40 "
                      f"for the bottleneck history that got timing here).")
        lines.append("")
    if worst_hold:
        lines.append(f"Worst hold path: slack **{worst_hold['slack_ns']:.3f} ns** — "
                      f"`{worst_hold['source']}` → `{worst_hold['destination']}`.")
        lines.append("")
    lines.append("**Caveat (see master spec S0 / D40, and the Opus review that prompted this")
    lines.append("script): 0.141 ns of setup margin on an 8 ns period is 1.8% — real but thin.")
    lines.append("`constraints/tob_timing.xdc` sets no `set_input_delay`/`set_output_delay` on")
    lines.append("RGMII, so the 31,058 timed endpoints above are internal paths only; the")
    lines.append("source-synchronous PHY interface itself is unconstrained and unmeasured here.**")
    lines.append("")
    (OUT_DIR / "timing.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return True


def write_utilization_md(util_text):
    u = parse_utilization(util_text)
    if not any(u.values()):
        print("WARN: could not parse utilization table from utilization.rpt", file=sys.stderr)
        return False

    lines = []
    lines.append("# results/utilization.md")
    lines.append("")
    lines.append("Generated by `scripts/report.py` from `results/build/utilization.rpt`")
    lines.append("(real Vivado `report_utilization` output, post-implementation/routed, on")
    lines.append("`xc7a35tfgg484-2`, per master spec S12.2). Do not hand-edit.")
    lines.append("")
    lines.append("| Resource | Used | Available | Utilization |")
    lines.append("| :-- | --: | --: | --: |")
    lines.append(fmt_row("Slice LUTs", u["lut"]))
    lines.append(fmt_row("Slice Registers (FF)", u["ff"]))
    lines.append(fmt_row("Block RAM Tile", u["bram"]))
    lines.append(fmt_row("DSPs", u["dsp"]))
    lines.append("")
    lines.append("**DSP usage is 0 for the whole design, classifier included** — this is a")
    lines.append("placeholder-classifier artifact, not a demonstrated DSP budget: `model/`'s")
    lines.append("weights are the documented S4 placeholder (`w_i=1`, bias=0, see CLAUDE.md /")
    lines.append("`docs/design_decisions.md`), so Vivado maps the int8x8 products to LUTs and")
    lines.append("trivially reduces the multiply-by-one classifier away entirely. The `<=8 DSP`")
    lines.append("classifier budget (S7.3) is met vacuously until a real trained model lands (S4).")
    lines.append("")
    lines.append("**`csr_block.v` is the single largest hand-written contributor to LUT usage**")
    lines.append("— 2,335 LUTs / 2,253 FFs, 11.2% of the part's entire LUT fabric, measured via")
    lines.append("`report_utilization -hierarchical -hierarchical_depth 2` on the routed D40")
    lines.append("netlist (`docs/design_decisions.md` D41). Root cause and a proposed fix (a")
    lines.append("shared-incrementer counter file + pipelined read mux, ~1,500+ LUTs recoverable)")
    lines.append("are documented there, not yet implemented.")
    lines.append("")
    (OUT_DIR / "utilization.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return True


def main():
    timing_text = read("timing_summary.rpt")
    util_text = read("utilization.rpt")

    if timing_text is None and util_text is None:
        print(f"No Vivado reports found in {BUILD_DIR} -- run scripts/build.tcl first.", file=sys.stderr)
        return 1

    ok = True
    if timing_text is not None:
        ok &= write_timing_md(timing_text)
    else:
        print("WARN: results/build/timing_summary.rpt not found, skipping timing.md", file=sys.stderr)

    if util_text is not None:
        ok &= write_utilization_md(util_text)
    else:
        print("WARN: results/build/utilization.rpt not found, skipping utilization.md", file=sys.stderr)

    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
