`timescale 1ns / 1ps

// S2 milestone gate: "1M-message parse, zero loss" (master spec S15 S2
// row) -- distinct from the four directed tests in tb_frame_classifier.v/
// tb_md_parser.v. Chains frame_classifier.v -> md_parser.v (the same
// order they sit in on the real datapath) and streams
// tb/stimulus/s2_soak.mem (generated by sim/gen_soak_vectors.py, which
// reuses feed_gen.py's "normal" scenario -- one well-formed 16-byte QUOTE
// per frame) through them: 1,000,000 well-formed single-message frames,
// back to back with a small inter-frame gap.
//
// Checks, per S10's counter-conservation philosophy applied to just this
// stage: every message sent produces exactly one msg_valid pulse, zero
// err_frame_len/err_msg_type/err_flags pulses (the "normal" scenario never
// corrupts anything -- that's what T05/T06 are for), and every 10,000th
// decoded message's fields match the raw input bytes at that message's
// offset in the loaded memory exactly (bit-exact spot-check directly
// against the wire bytes, not a second golden-model reimplementation,
// since the wire format is self-describing at known byte offsets -- S4.3).
//
// Run with (allow several minutes; 1,000,000 messages is 16,000,000+
// clock cycles of streaming):
//   iverilog -g2001 -Wall -o parser_soak_tb.vvp rtl/frame_classifier.v rtl/md_parser.v tb/tb_parser_soak.v
//   vvp parser_soak_tb.vvp
//
// Verilog-2001 only.

module tb_parser_soak;

    localparam integer NUM_MESSAGES = 1_000_000;
    localparam integer MSG_BYTES    = 16;
    localparam integer TOTAL_BYTES  = NUM_MESSAGES * MSG_BYTES;
    localparam integer SPOT_CHECK_STRIDE = 10_000;   // verify fields every Nth message

    reg clk = 1'b0;
    always #4 clk = ~clk;   // 125 MHz

    reg rst_n = 1'b0;

    // ---- stimulus memory, loaded from sim/gen_soak_vectors.py's output ----
    reg [7:0] mem [0:TOTAL_BYTES-1];

    initial $readmemh("tb/stimulus/s2_soak.mem", mem);

    // ---- frame_classifier inputs ----
    reg [7:0]  rx_data     = 8'd0;
    reg        rx_valid    = 1'b0;
    reg        frame_start = 1'b0;
    reg [15:0] rx_len      = 16'd0;

    wire [7:0] fc_out_data;
    wire       fc_out_valid;
    wire       err_frame_len;

    frame_classifier fc (
        .clk           (clk),
        .rst_n         (rst_n),
        .rx_data       (rx_data),
        .rx_valid      (rx_valid),
        .frame_start   (frame_start),
        .rx_len        (rx_len),
        .out_data      (fc_out_data),
        .out_valid     (fc_out_valid),
        .err_frame_len (err_frame_len)
    );

    wire        msg_valid;
    wire [7:0]  msg_type, msg_symbol_id, msg_side, msg_flags;
    wire [31:0] msg_price, msg_quantity, msg_seq_num;
    wire        err_msg_type, err_flags;

    md_parser mp (
        .clk           (clk),
        .rst_n         (rst_n),
        .in_data       (fc_out_data),
        .in_valid      (fc_out_valid),
        .msg_valid     (msg_valid),
        .msg_type      (msg_type),
        .msg_symbol_id (msg_symbol_id),
        .msg_side      (msg_side),
        .msg_flags     (msg_flags),
        .msg_price     (msg_price),
        .msg_quantity  (msg_quantity),
        .msg_seq_num   (msg_seq_num),
        .err_msg_type  (err_msg_type),
        .err_flags     (err_flags)
    );

    integer msg_count;
    integer err_frame_len_count;
    integer err_msg_type_count;
    integer err_flags_count;
    integer spot_check_fail;

    reg [127:0] expect_frame;
    integer     base;

    always @(posedge clk) begin
        if (msg_valid) begin
            // Spot-check every SPOT_CHECK_STRIDE-th message's fields
            // directly against the raw bytes it was built from.
            if ((msg_count % SPOT_CHECK_STRIDE) == 0) begin
                base = msg_count * MSG_BYTES;
                expect_frame = {mem[base+0],  mem[base+1],  mem[base+2],  mem[base+3],
                                 mem[base+4],  mem[base+5],  mem[base+6],  mem[base+7],
                                 mem[base+8],  mem[base+9],  mem[base+10], mem[base+11],
                                 mem[base+12], mem[base+13], mem[base+14], mem[base+15]};
                if (msg_type      !== expect_frame[127:120] ||
                    msg_symbol_id !== expect_frame[119:112] ||
                    msg_side      !== expect_frame[111:104] ||
                    msg_flags     !== expect_frame[103:96]  ||
                    msg_price     !== expect_frame[95:64]   ||
                    msg_quantity  !== expect_frame[63:32]   ||
                    msg_seq_num   !== expect_frame[31:0]) begin
                    $display("FAIL: message %0d field mismatch vs. raw bytes at offset %0d", msg_count, base);
                    spot_check_fail = spot_check_fail + 1;
                end
            end
            msg_count = msg_count + 1;
        end
        if (err_frame_len) err_frame_len_count = err_frame_len_count + 1;
        if (err_msg_type)  err_msg_type_count  = err_msg_type_count  + 1;
        if (err_flags)     err_flags_count     = err_flags_count     + 1;
    end

    integer f, b;
    reg     fail;

    initial begin
        msg_count           = 0;
        err_frame_len_count = 0;
        err_msg_type_count  = 0;
        err_flags_count     = 0;
        spot_check_fail     = 0;
        fail                = 1'b0;

        rst_n = 1'b0;
        #20;
        rst_n = 1'b1;
        #20;

        for (f = 0; f < NUM_MESSAGES; f = f + 1) begin
            @(negedge clk);
            frame_start = 1'b1;
            rx_len      = MSG_BYTES[15:0];
            @(posedge clk);
            #1;
            frame_start = 1'b0;
            for (b = 0; b < MSG_BYTES; b = b + 1) begin
                @(negedge clk);
                rx_valid = 1'b1;
                rx_data  = mem[f * MSG_BYTES + b];
            end
            @(negedge clk);
            rx_valid = 1'b0;
            @(negedge clk);   // small inter-frame gap
            @(negedge clk);
        end

        // Drain: give md_parser/frame_classifier a few cycles to finish
        // the last message's msg_valid pulse.
        repeat (8) @(posedge clk);

        if (msg_count !== NUM_MESSAGES) begin
            $display("FAIL: msg_count=%0d, expected %0d (zero loss)", msg_count, NUM_MESSAGES);
            fail = 1'b1;
        end
        if (err_frame_len_count !== 0) begin
            $display("FAIL: err_frame_len fired %0d times, expected 0", err_frame_len_count);
            fail = 1'b1;
        end
        if (err_msg_type_count !== 0) begin
            $display("FAIL: err_msg_type fired %0d times, expected 0", err_msg_type_count);
            fail = 1'b1;
        end
        if (err_flags_count !== 0) begin
            $display("FAIL: err_flags fired %0d times, expected 0", err_flags_count);
            fail = 1'b1;
        end
        if (spot_check_fail !== 0) begin
            $display("FAIL: %0d spot-checked messages had field mismatches", spot_check_fail);
            fail = 1'b1;
        end

        if (fail) begin
            $display("FAIL");
            $finish;
        end
        $display("PASS: %0d messages, zero loss, zero spurious errors", msg_count);
        $finish;
    end

endmodule
